#!/bin/bash
#  Development script for saving models (and picking up updated
#  ones) on Dropbox so I can have multiple machines working on
#  tuning models.optimized remotely. 
#  I'll copy any changed models to Dropbox every 10 minutes.

echo " "
echo "Background syncing models with Dropbox every 10 minutes."
echo " "

ok=1
if [ "$#" -eq 1 ]
then
  if [ "$1" == "dark" ]
  then
    echo "Turning off screen.  Move mouse to wake me up again."
    sleep 2
    xset dpms force off
  else
    echo "Sorry, but I don't know about any $1 option."
    ok=0
  fi
else
  if [ "$#" -gt 1 ] 
  then
    ok=0
    echo "Wrong number of args.  Back to school for you!"
  fi
fi

if [ "$ok" -eq 0 ]
then
  echo " "
  echo "Usage:"
  echo " "
  echo "      bash/babysit [dark] "
  echo " "
  echo "This sends the quotes, jokes, and fakenews models to Dropbox"
  echo "if ours is more recent than the one(s) there, and copies the"
  echo "other direction if the Dropbox copy is more recent."
  echo " "
  echo "The optional 'dark' parameter is used if you want the screen"
  echo "to go dark while this is running."
  echo " "
  exit 1
fi


# Let's actually do some work now.

while true
do 
  #cp -u models/quotes/*    ~/Dropbox/deeptext/models/quotes
  #cp -u models/jokes/*     ~/Dropbox/deeptext/models/jokes
  cp -up models/fakenews/*  ~/Dropbox/deeptext/models/fakenews
  sleep 300
  
  cp -up ~/Dropbox/deeptext/models/quotes/*   models/quotes
  cp -up ~/Dropbox/deeptext/models/jokes/*    models/jokes
  #cp -u ~/Dropbox/deeptext/models/fakenews/* models/fakenews
  sleep 300
done

